<?php

namespace Database\Seeders;

use App\Models\Kategori;
use App\Models\Produk;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class Import150ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['kode' => 'PRD-EX-001', 'nama' => '99 KULIT PANGSIT', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 31, 'min' => 10, 'sat' => 'Pcs', 'desk' => '99 KULIT PANGSIT berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-002', 'nama' => 'ABON AYAM KARWATI ORI 250GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ABON AYAM KARWATI ORI 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-003', 'nama' => 'ABON AYAM KARWATI PEDAS 250GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 38, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ABON AYAM KARWATI PEDAS 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-004', 'nama' => 'ADABI SOS KOREA', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 73, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ADABI SOS KOREA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-005', 'nama' => 'ADABI TOMYAM', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 35, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ADABI TOMYAM berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-006', 'nama' => 'AICE 8 LITER EMBER', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 32, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE 8 LITER EMBER berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-007', 'nama' => 'AKUMO NUGGET 250GR', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 35, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AKUMO NUGGET 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-008', 'nama' => 'ALFA ONE', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 44, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ALFA ONE berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-009', 'nama' => 'ALLANA DAGING KERBAU 1KG', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ALLANA DAGING KERBAU 1KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-010', 'nama' => 'AMROON 1 KG', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 65, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AMROON 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-011', 'nama' => 'ASIMO NUGGET 250GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 75, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'ASIMO NUGGET 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-012', 'nama' => 'AYAM UNGKEP 1 KG', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 56, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AYAM UNGKEP 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-013', 'nama' => 'AYAM UNGKEP 500 GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 58, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AYAM UNGKEP 500 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-014', 'nama' => 'B19 BAKSO AYAM 200GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 81, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'B19 BAKSO AYAM 200GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-015', 'nama' => 'B19 BAKSO BASRENG', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'B19 BAKSO BASRENG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-016', 'nama' => 'B19 BAKSO IKAN 250GR', 'kat' => 'Frozen Food', 'harga' => 18000, 'stok' => 74, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'B19 BAKSO IKAN 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-017', 'nama' => 'BAKPOW KARAKTER', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 51, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKPOW KARAKTER berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-018', 'nama' => 'BAKSO BASRENG RB', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 39, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO BASRENG RB berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-019', 'nama' => 'BAKSO BMS ISI 25', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO BMS ISI 25 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-020', 'nama' => 'Bakso Bul Bul Hijau', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 36, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Bakso Bul Bul Hijau berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-021', 'nama' => 'Bakso Bul bul Kuning', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Bakso Bul bul Kuning berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-022', 'nama' => 'Bakso Bul Bul Merah', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 52, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Bakso Bul Bul Merah berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-023', 'nama' => 'Bakso Bul Bul Ungu', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Bakso Bul Bul Ungu berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-024', 'nama' => 'BAKSO IMAN SA', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 81, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO IMAN SA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-025', 'nama' => 'BAKSO IMAN SAPI', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 76, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO IMAN SAPI berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-026', 'nama' => 'BAKSO JAWARA ISI 100', 'kat' => 'Frozen Food', 'harga' => 45000, 'stok' => 64, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO JAWARA ISI 100 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-027', 'nama' => 'BAKSO KAHIJI', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO KAHIJI berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-028', 'nama' => 'BAKSO MEKAR SARI KEMBANG JERUK', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 65, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO MEKAR SARI KEMBANG JERUK berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-029', 'nama' => 'BAKSO SEDAP DAGING CINCANG', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 83, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO SEDAP DAGING CINCANG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-030', 'nama' => 'BAKSO SEDAP SARI KEJU', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 66, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO SEDAP SARI KEJU berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-031', 'nama' => 'BAKSO SUMBER SELERA ORIGINAL', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 75, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO SUMBER SELERA ORIGINAL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-032', 'nama' => 'BAKSO TUSUK KIRANA', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 32, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO TUSUK KIRANA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-033', 'nama' => 'BARTOZ NUGGET 500GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 79, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BARTOZ NUGGET 500GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-034', 'nama' => 'BASRENG UMKM ALL VARIAN 250 GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 35, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BASRENG UMKM ALL VARIAN 250 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-035', 'nama' => 'BAWANG GORENG TOPLES KECIL', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 85, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAWANG GORENG TOPLES KECIL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-036', 'nama' => 'BE BEST DAGING KERBAU 1KG', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BE BEST DAGING KERBAU 1KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-037', 'nama' => 'BEBEK 1,3 KG', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 59, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BEBEK 1,3 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-038', 'nama' => 'BEBEK FROZEN 1,8 KG', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 40, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BEBEK FROZEN 1,8 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-039', 'nama' => 'BEBEK PEKING 1 KG', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 52, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BEBEK PEKING 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-040', 'nama' => 'BEBEK PEKING 2,1 KG', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 72, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BEBEK PEKING 2,1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-041', 'nama' => 'BELFOOD CHICKEN NUGGET AYAM 250GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 74, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD CHICKEN NUGGET AYAM 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-042', 'nama' => 'BELFOOD KENTANG 175GR', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD KENTANG 175GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-043', 'nama' => 'BELFOOD NUGGET CERIA 170GR', 'kat' => 'Frozen Food', 'harga' => 18000, 'stok' => 64, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET CERIA 170GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-044', 'nama' => 'BELFOOD NUGGET CERIA 500GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 40, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET CERIA 500GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-045', 'nama' => 'BELFOOD NUGGET SP 170GR', 'kat' => 'Frozen Food', 'harga' => 45000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET SP 170GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-046', 'nama' => 'BELFOOD NUGGET STIK 170GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 70, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET STIK 170GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-047', 'nama' => 'BELFOOD NUGGET UENAK 220GR', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 44, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET UENAK 220GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-048', 'nama' => 'BELFOOD NUGGET UENAK 500GR', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 83, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD NUGGET UENAK 500GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-049', 'nama' => 'BELFOOD ROYAL NUGGET 470GR', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 44, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD ROYAL NUGGET 470GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-050', 'nama' => 'BELFOOD SOSIS  475 gr ISI 15', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 81, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD SOSIS  475 gr ISI 15 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-051', 'nama' => 'BELFOOD SOSIS AYAM 200GR', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 55, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD SOSIS AYAM 200GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-052', 'nama' => 'BELFOOD SOSIS ISI 30', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 34, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELFOOD SOSIS ISI 30 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-053', 'nama' => 'BELIBIS  SAUS TOMAT 340ML', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 66, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELIBIS  SAUS TOMAT 340ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-054', 'nama' => 'BELIBIS SAUS CABE 135ML', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 43, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELIBIS SAUS CABE 135ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-055', 'nama' => 'BELIBIS SAUS CABE 1KG', 'kat' => 'Frozen Food', 'harga' => 45000, 'stok' => 55, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELIBIS SAUS CABE 1KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-056', 'nama' => 'BELIBIS SAUS CABE 340ML', 'kat' => 'Frozen Food', 'harga' => 45000, 'stok' => 39, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELIBIS SAUS CABE 340ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-057', 'nama' => 'BELIBIS SAUS TOMAT 135ML', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 38, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELIBIS SAUS TOMAT 135ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-058', 'nama' => 'BELLA WHITE CHOCOLATE 250GR', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 77, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BELLA WHITE CHOCOLATE 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-059', 'nama' => 'BERKAT', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 64, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BERKAT berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-060', 'nama' => 'BMS ISI 50', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 77, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BMS ISI 50 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-061', 'nama' => 'BOBA 1 KG', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 67, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BOBA 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-062', 'nama' => 'BOLEN KUJANG', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 53, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BOLEN KUJANG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-063', 'nama' => 'BOLEN LEMBANG KANG SULE', 'kat' => 'Frozen Food', 'harga' => 22000, 'stok' => 38, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BOLEN LEMBANG KANG SULE berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-064', 'nama' => 'BON CABE LV 10 BOTOL 4,5 G', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 61, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE LV 10 BOTOL 4,5 G berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-065', 'nama' => 'BON CABE NORI SACHET', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE NORI SACHET berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-066', 'nama' => 'BONANZA', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 85, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BONANZA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-067', 'nama' => 'BONBON SOSIS 1KG', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 39, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BONBON SOSIS 1KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-068', 'nama' => 'BONBON SOSIS 500GR', 'kat' => 'Frozen Food', 'harga' => 18000, 'stok' => 80, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BONBON SOSIS 500GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-069', 'nama' => 'BONEKA + KOPER OCT-84018', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BONEKA + KOPER OCT-84018 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-070', 'nama' => 'BOSQUE SOSIS BAKAR MINI', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BOSQUE SOSIS BAKAR MINI berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-071', 'nama' => 'BRAVO DAGING RENDANG 1 KG', 'kat' => 'Frozen Food', 'harga' => 38000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BRAVO DAGING RENDANG 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-072', 'nama' => 'BUBBLE JELLY', 'kat' => 'Frozen Food', 'harga' => 45000, 'stok' => 63, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUBBLE JELLY berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-073', 'nama' => 'BUMBU BAKSO SONY', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 65, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUMBU BAKSO SONY berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-074', 'nama' => 'BUMIFOOD CRAB STIK 50 G', 'kat' => 'Frozen Food', 'harga' => 12000, 'stok' => 73, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUMIFOOD CRAB STIK 50 G berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-075', 'nama' => 'BUMIFOOD FISH TOFU 60 GR', 'kat' => 'Frozen Food', 'harga' => 15000, 'stok' => 73, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUMIFOOD FISH TOFU 60 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-076', 'nama' => 'BUMIFOOD ODENG 60 GR', 'kat' => 'Frozen Food', 'harga' => 52000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUMIFOOD ODENG 60 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-077', 'nama' => 'BUN MINI', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 79, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUN MINI berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-078', 'nama' => 'BUN WIJEN', 'kat' => 'Frozen Food', 'harga' => 32000, 'stok' => 37, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUN WIJEN berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-079', 'nama' => 'CEDEA BAKSO SALMON 500GR', 'kat' => 'Frozen Food', 'harga' => 25000, 'stok' => 57, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CEDEA BAKSO SALMON 500GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-080', 'nama' => 'CEDEA CHIKUWA LONG 1KG', 'kat' => 'Frozen Food', 'harga' => 18000, 'stok' => 59, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CEDEA CHIKUWA LONG 1KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-081', 'nama' => 'BAKSO  BAHARI IKAN + AYAM', 'kat' => 'Makanan', 'harga' => 12000, 'stok' => 76, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO  BAHARI IKAN + AYAM berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-082', 'nama' => 'BAKSO IKAN SINAR BAHARI ISI 10', 'kat' => 'Makanan', 'harga' => 25000, 'stok' => 62, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO IKAN SINAR BAHARI ISI 10 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-083', 'nama' => 'BAKSO SUMBER SELERA KEJU', 'kat' => 'Makanan', 'harga' => 18000, 'stok' => 62, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO SUMBER SELERA KEJU berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-084', 'nama' => 'Barcelona 1 kg', 'kat' => 'Makanan', 'harga' => 15000, 'stok' => 85, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Barcelona 1 kg berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-085', 'nama' => 'Barcelona 100 g', 'kat' => 'Makanan', 'harga' => 25000, 'stok' => 83, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Barcelona 100 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-086', 'nama' => 'Barcelona 250 g', 'kat' => 'Makanan', 'harga' => 52000, 'stok' => 68, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Barcelona 250 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-087', 'nama' => 'barcelona 50 g', 'kat' => 'Makanan', 'harga' => 22000, 'stok' => 39, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'barcelona 50 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-088', 'nama' => 'barcelona 500 g', 'kat' => 'Makanan', 'harga' => 32000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'barcelona 500 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-089', 'nama' => 'Basreng 50 g', 'kat' => 'Makanan', 'harga' => 18000, 'stok' => 64, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng 50 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-090', 'nama' => 'Basreng Origina 1 kg', 'kat' => 'Makanan', 'harga' => 52000, 'stok' => 30, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng Origina 1 kg berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-091', 'nama' => 'Basreng Origina 100 g', 'kat' => 'Makanan', 'harga' => 32000, 'stok' => 61, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng Origina 100 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-092', 'nama' => 'Basreng Origina 250 g', 'kat' => 'Makanan', 'harga' => 12000, 'stok' => 37, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng Origina 250 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-093', 'nama' => 'Basreng Origina 50 g', 'kat' => 'Makanan', 'harga' => 32000, 'stok' => 83, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng Origina 50 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-094', 'nama' => 'Basreng Origina 500 g', 'kat' => 'Makanan', 'harga' => 25000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'Basreng Origina 500 g berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-095', 'nama' => 'BASRENG TOPLES  500 GR', 'kat' => 'Makanan', 'harga' => 12000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BASRENG TOPLES  500 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-096', 'nama' => 'BASRENG TOPLES 1 KG', 'kat' => 'Makanan', 'harga' => 15000, 'stok' => 35, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BASRENG TOPLES 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-097', 'nama' => 'BASRENG TOPLES 250 GR', 'kat' => 'Makanan', 'harga' => 45000, 'stok' => 82, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BASRENG TOPLES 250 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-098', 'nama' => 'BIKA AMBON', 'kat' => 'Makanan', 'harga' => 15000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BIKA AMBON berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-099', 'nama' => 'BOLU BANDUNG', 'kat' => 'Makanan', 'harga' => 52000, 'stok' => 79, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BOLU BANDUNG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-100', 'nama' => 'BON CABE LV 15 BOTOL', 'kat' => 'Makanan', 'harga' => 18000, 'stok' => 38, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE LV 15 BOTOL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-101', 'nama' => 'BON CABE LV 30', 'kat' => 'Makanan', 'harga' => 45000, 'stok' => 65, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE LV 30 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-102', 'nama' => 'BON CABE LV 30 SACHET 4,5 G', 'kat' => 'Makanan', 'harga' => 18000, 'stok' => 46, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE LV 30 SACHET 4,5 G berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-103', 'nama' => 'BON CABE LV 50 MAXED SACHET 2,5 G', 'kat' => 'Makanan', 'harga' => 52000, 'stok' => 85, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BON CABE LV 50 MAXED SACHET 2,5 G berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-104', 'nama' => 'BUMBU PECEL SINTI 100GR', 'kat' => 'Makanan', 'harga' => 38000, 'stok' => 43, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BUMBU PECEL SINTI 100GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-105', 'nama' => 'CABE KERING 250GR', 'kat' => 'Makanan', 'harga' => 52000, 'stok' => 78, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CABE KERING 250GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-106', 'nama' => 'ASTOR ALL VARIAN', 'kat' => 'Cemilan', 'harga' => 22000, 'stok' => 75, 'min' => 10, 'sat' => 'Toples', 'desk' => 'ASTOR ALL VARIAN berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-107', 'nama' => 'ASTOR ALL VARIAN 250 GR', 'kat' => 'Cemilan', 'harga' => 25000, 'stok' => 55, 'min' => 10, 'sat' => 'Toples', 'desk' => 'ASTOR ALL VARIAN 250 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-108', 'nama' => 'BOLA PELANGI', 'kat' => 'Cemilan', 'harga' => 32000, 'stok' => 58, 'min' => 10, 'sat' => 'Toples', 'desk' => 'BOLA PELANGI berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-109', 'nama' => 'DODOL KERTAS EKA SARI 1 KG', 'kat' => 'Cemilan', 'harga' => 52000, 'stok' => 58, 'min' => 10, 'sat' => 'Toples', 'desk' => 'DODOL KERTAS EKA SARI 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-110', 'nama' => 'DODOL KERTAS EKASARI 250 GR', 'kat' => 'Cemilan', 'harga' => 15000, 'stok' => 45, 'min' => 10, 'sat' => 'Toples', 'desk' => 'DODOL KERTAS EKASARI 250 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-111', 'nama' => 'DODOL KERTAS EKSARI 500 GR', 'kat' => 'Cemilan', 'harga' => 22000, 'stok' => 34, 'min' => 10, 'sat' => 'Toples', 'desk' => 'DODOL KERTAS EKSARI 500 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-112', 'nama' => 'DODOL WARNA', 'kat' => 'Cemilan', 'harga' => 32000, 'stok' => 31, 'min' => 10, 'sat' => 'Toples', 'desk' => 'DODOL WARNA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-113', 'nama' => 'GEM KEMBANG BALL', 'kat' => 'Cemilan', 'harga' => 52000, 'stok' => 44, 'min' => 10, 'sat' => 'Toples', 'desk' => 'GEM KEMBANG BALL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-114', 'nama' => 'JELI INACO 1 KG', 'kat' => 'Cemilan', 'harga' => 22000, 'stok' => 30, 'min' => 10, 'sat' => 'Toples', 'desk' => 'JELI INACO 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-115', 'nama' => 'JELI INACO 500 GR', 'kat' => 'Cemilan', 'harga' => 15000, 'stok' => 75, 'min' => 10, 'sat' => 'Toples', 'desk' => 'JELI INACO 500 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-116', 'nama' => 'HASAN ISI 6', 'kat' => 'Cemilan', 'harga' => 12000, 'stok' => 44, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'HASAN ISI 6 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-117', 'nama' => 'HASANAH ISI 6', 'kat' => 'Cemilan', 'harga' => 15000, 'stok' => 32, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'HASANAH ISI 6 berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-118', 'nama' => 'JELI BIT 1 KG', 'kat' => 'Cemilan', 'harga' => 32000, 'stok' => 34, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'JELI BIT 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-119', 'nama' => 'JELI BIT 500 GR', 'kat' => 'Cemilan', 'harga' => 52000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'JELI BIT 500 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-120', 'nama' => 'KACANG ATOM 100 GR', 'kat' => 'Cemilan', 'harga' => 25000, 'stok' => 72, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'KACANG ATOM 100 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-121', 'nama' => 'AICE 2 COLORS', 'kat' => 'Es Krim', 'harga' => 45000, 'stok' => 43, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE 2 COLORS berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-122', 'nama' => 'AICE CHOCOLATE CRISPY', 'kat' => 'Es Krim', 'harga' => 52000, 'stok' => 38, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE CHOCOLATE CRISPY berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-123', 'nama' => 'AICE COFEE CRISPY', 'kat' => 'Es Krim', 'harga' => 45000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE COFEE CRISPY berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-124', 'nama' => 'AICE EMBER 5 LITER', 'kat' => 'Es Krim', 'harga' => 45000, 'stok' => 81, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE EMBER 5 LITER berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-125', 'nama' => 'AICE EMBER 8 LITER', 'kat' => 'Es Krim', 'harga' => 38000, 'stok' => 42, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'AICE EMBER 8 LITER berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-126', 'nama' => 'CIMORY BITES 120 ML', 'kat' => 'Minuman', 'harga' => 15000, 'stok' => 36, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CIMORY BITES 120 ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-127', 'nama' => 'CIMORY EATMILK', 'kat' => 'Minuman', 'harga' => 38000, 'stok' => 52, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CIMORY EATMILK berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-128', 'nama' => 'CIMORY PORORO 325 ML', 'kat' => 'Minuman', 'harga' => 38000, 'stok' => 56, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CIMORY PORORO 325 ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-129', 'nama' => 'CIMORY SQUEZE', 'kat' => 'Minuman', 'harga' => 45000, 'stok' => 85, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CIMORY SQUEZE berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-130', 'nama' => 'CIMORY UHT 125 ML', 'kat' => 'Minuman', 'harga' => 12000, 'stok' => 73, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'CIMORY UHT 125 ML berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-131', 'nama' => 'BAKSO MOZZARELLA', 'kat' => 'Menu Bakso', 'harga' => 15000, 'stok' => 33, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO MOZZARELLA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-132', 'nama' => 'BAKSO PENTOL KECIL', 'kat' => 'Menu Bakso', 'harga' => 38000, 'stok' => 76, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO PENTOL KECIL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-133', 'nama' => 'BAKSO RUSUK', 'kat' => 'Menu Bakso', 'harga' => 32000, 'stok' => 81, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO RUSUK berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-134', 'nama' => 'BAKSO RUSUK BIASA', 'kat' => 'Menu Bakso', 'harga' => 15000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO RUSUK BIASA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-135', 'nama' => 'BAKSO RUSUK JUMBO', 'kat' => 'Menu Bakso', 'harga' => 22000, 'stok' => 42, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'BAKSO RUSUK JUMBO berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-136', 'nama' => 'bakso bul"', 'kat' => 'Pertopingan', 'harga' => 52000, 'stok' => 58, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'bakso bul" berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-137', 'nama' => 'bintang', 'kat' => 'Pertopingan', 'harga' => 18000, 'stok' => 57, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'bintang berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-138', 'nama' => 'bola  salmon', 'kat' => 'Pertopingan', 'harga' => 18000, 'stok' => 47, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'bola  salmon berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-139', 'nama' => 'chikua', 'kat' => 'Pertopingan', 'harga' => 45000, 'stok' => 45, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'chikua berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-140', 'nama' => 'duo flowers', 'kat' => 'Pertopingan', 'harga' => 15000, 'stok' => 58, 'min' => 10, 'sat' => 'Pcs', 'desk' => 'duo flowers berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-141', 'nama' => 'ADABI REMPAH SUP TULANG 13 GR', 'kat' => 'Bumbu', 'harga' => 52000, 'stok' => 36, 'min' => 10, 'sat' => 'Pack', 'desk' => 'ADABI REMPAH SUP TULANG 13 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-142', 'nama' => 'ASAM JAWA', 'kat' => 'Bumbu', 'harga' => 12000, 'stok' => 71, 'min' => 10, 'sat' => 'Pack', 'desk' => 'ASAM JAWA berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-143', 'nama' => 'BIJI PALA 37 GR', 'kat' => 'Bumbu', 'harga' => 52000, 'stok' => 83, 'min' => 10, 'sat' => 'Pack', 'desk' => 'BIJI PALA 37 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-144', 'nama' => 'DEL MONTE BBQ 250 GR', 'kat' => 'Saos', 'harga' => 12000, 'stok' => 35, 'min' => 10, 'sat' => 'Pack', 'desk' => 'DEL MONTE BBQ 250 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-145', 'nama' => 'DEL MONTE EXTRA HOT SACHET 8 GR', 'kat' => 'Saos', 'harga' => 22000, 'stok' => 40, 'min' => 10, 'sat' => 'Pack', 'desk' => 'DEL MONTE EXTRA HOT SACHET 8 GR berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-146', 'nama' => 'DUA BELIBIS SAOS CABE 1 KG', 'kat' => 'Saos', 'harga' => 38000, 'stok' => 61, 'min' => 10, 'sat' => 'Pack', 'desk' => 'DUA BELIBIS SAOS CABE 1 KG berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-147', 'nama' => '156 MOBIL TUMBLING', 'kat' => 'Mainan Anak', 'harga' => 45000, 'stok' => 43, 'min' => 10, 'sat' => 'Pcs', 'desk' => '156 MOBIL TUMBLING berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-148', 'nama' => '627-8 PAW PATROL', 'kat' => 'Mainan Anak', 'harga' => 38000, 'stok' => 33, 'min' => 10, 'sat' => 'Pcs', 'desk' => '627-8 PAW PATROL berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-149', 'nama' => '6602B BONEKA PADAT', 'kat' => 'Mainan Anak', 'harga' => 18000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => '6602B BONEKA PADAT berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-EX-150', 'nama' => '99-818 PISTOL RAMBO', 'kat' => 'Mainan Anak', 'harga' => 12000, 'stok' => 54, 'min' => 10, 'sat' => 'Pcs', 'desk' => '99-818 PISTOL RAMBO berkualitas & segar khas Della Frozen Mart.'],
            ['kode' => 'PRD-0214', 'nama' => 'Bumbu rendang', 'kat' => 'Bumbu', 'harga' => 10000, 'stok' => 25, 'min' => 5, 'sat' => 'Pack', 'desk' => 'Bumbu rendang berkualitas khas Della Frozen Mart.'],
            ['kode' => 'PRD-0215', 'nama' => 'Bumbu opor', 'kat' => 'Bumbu', 'harga' => 5000, 'stok' => 20, 'min' => 5, 'sat' => 'Pack', 'desk' => 'Bumbu opor berkualitas khas Della Frozen Mart.'],
        ];

        $imgMap = [
            'PRD-001' => 'products/prd_001_kanzler_sosis_sapi_500gr.png',
            'PRD-002' => 'products/prd_002_kanzler_sosis_ayam_500gr.png',
            'PRD-003' => 'products/prd_003_champ_sosis_ayam_375gr.png',
            'PRD-004' => 'products/prd_004_kimbo_sosis_sapi_500gr.png',
            'PRD-005' => 'products/prd_005_so_good_sosis_keju_375gr.png',
            'PRD-006' => 'products/prd_006_bernardi_sosis_sapi_jumbo_500g.png',
            'PRD-007' => 'products/prd_007_sozzis_sosis_mini_isi_20pcs.png',
            'PRD-008' => 'products/prd_008_fiesta_nugget_ayam_250gr.png',
            'PRD-009' => 'products/prd_009_fiesta_nugget_ayam_500gr.png',
            'PRD-010' => 'products/prd_010_so_good_nugget_ayam_400gr.png',
            'PRD-011' => 'products/prd_011_champ_nugget_ayam_400gr.png',
            'PRD-012' => 'products/prd_012_sajiku_nugget_ikan_250gr.png',
            'PRD-013' => 'products/prd_013_bernardi_chicken_fingers_250gr.png',
            'PRD-025' => 'products/prd_014_crabstick_frozen_250gr.png',
            'PRD-026' => 'products/prd_015_otak_otak_ikan_frozen_10pcs.png',
            'PRD-027' => 'products/prd_016_fish_roll_frozen_250gr.png',
            'PRD-028' => 'products/prd_017_udang_kupas_frozen_300gr.png',
            'PRD-029' => 'products/prd_018_cumi_frozen_300gr.png',
            'PRD-030' => 'products/prd_019_scallop_frozen_200gr.png',
            'PRD-031' => 'products/prd_020_dimsum_ayam_frozen_10pcs.png',
            'PRD-032' => 'products/prd_021_dimsum_udang_frozen_10pcs.png',
            'PRD-033' => 'products/prd_022_siomay_ayam_frozen_10pcs.png',
            'PRD-038' => 'products/prd_023_gyoza_ayam_frozen_10pcs.png',
            'PRD-039' => 'products/prd_024_shumai_udang_frozen_10pcs.png',
            'PRD-014' => 'products/prd_025_bakso_sapi_frozen_50_butir.png',
            'PRD-015' => 'products/prd_026_bakso_sapi_premium_25_butir.png',
            'PRD-016' => 'products/prd_027_bakso_ayam_frozen_50_butir.png',
            'PRD-017' => 'products/prd_028_bakso_ikan_frozen_30_butir.png',
            'PRD-018' => 'products/prd_029_baso_aci_sapi_frozen_300gr.png',
            'PRD-040' => 'products/prd_030_tahu_bakso_frozen_10pcs.png',
            'PRD-034' => 'products/prd_031_bakpao_isi_ayam_frozen_5pcs.png',
            'PRD-035' => 'products/prd_032_bakpao_isi_coklat_frozen_5pcs.png',
            'PRD-036' => 'products/prd_033_lumpia_sayur_frozen_10pcs.png',
            'PRD-037' => 'products/prd_034_pangsit_goreng_frozen_20pcs.png',
            'PRD-041' => 'products/prd_035_nasi_bento_chicken_katsu.png',
            'PRD-020' => 'products/prd_036_kentang_goreng_crinkle_1kg.png',
            'PRD-021' => 'products/prd_037_kentang_goreng_stick_1kg.png',
            'PRD-022' => 'products/prd_038_tambora_kentang_wedges_1kg.png',
            'PRD-019' => 'products/prd_039_cimol_frozen_500gr.png',
            'PRD-023' => 'products/prd_040_sayur_mix_frozen_500gr.png',
            'PRD-024' => 'products/prd_041_edamame_frozen_500gr.png',
            'PRD-042' => 'products/prd_042_risol_mayo_frozen_10pcs.png',
            'PRD-043' => 'products/prd_043_bumbu_kuah_bakso_mamasuka_100g.png',
            'PRD-044' => 'products/prd_044_bumbu_tabur_balado_antaka_100g.png',
            'PRD-045' => 'products/prd_045_bumbu_racik_ayam_goreng_indofo.png',
            'PRD-046' => 'products/prd_046_es_krim_walls_feast_cokelat_65.png',
            'PRD-047' => 'products/prd_047_es_krim_aice_mochi_vanilla_45g.png',
            'PRD-048' => 'products/prd_048_es_krim_campina_hula_hula_kaca.png',
            'PRD-049' => 'products/prd_049_keju_mozzarella_parut_kraft_16.png',
            'PRD-050' => 'products/prd_050_mayonaise_mamasuka_pouch_480g.png',
            'PRD-051' => 'products/prd_051_nori_rumput_laut_tabur_30g.png',
            'PRD-052' => 'products/prd_052_tusuk_sate_bakso_kayu_200g.png',
            'PRD-053' => 'products/prd_053_thinwall_box_makanan_500ml_10p.png',
            'PRD-054' => 'products/prd_054_kantong_plastik_ziplock_isi_20.png',
            'PRD-055' => 'products/prd_055_teh_pucuk_harum_botol_350ml.png',
            'PRD-056' => 'products/prd_056_ultra_milk_susu_uht_cokelat_25.png',
            'PRD-057' => 'products/prd_057_milk_tea_boba_frozen_250ml.png',
            'PRD-058' => 'products/prd_058_saos_sambal_extra_pedas_del_mo.png',
            'PRD-059' => 'products/prd_059_saos_tomat_abc_botol_335ml.png',
            'PRD-060' => 'products/prd_060_saos_tiram_saori_botol_133ml.png',
            'PRD-061' => 'products/prd_061_mainan_figur_mini_superhero.png',
            'PRD-062' => 'products/prd_062_mainan_gelembung_sabun_bubble_.png',
            'PRD-063' => 'products/prd_063_mainan_puzzle_edukasi_kayu_ana.png',
            'PRD-EX-001' => 'products/prd_064_99_kulit_pangsit.png',
            'PRD-EX-002' => 'products/prd_065_abon_ayam_karwati_ori_250gr.png',
            'PRD-EX-003' => 'products/prd_066_abon_ayam_karwati_pedas_250gr.png',
            'PRD-EX-004' => 'products/prd_067_adabi_sos_korea.png',
            'PRD-EX-005' => 'products/prd_068_adabi_tomyam.png',
            'PRD-EX-006' => 'products/prd_069_aice_8_liter_ember.png',
            'PRD-EX-007' => 'products/prd_070_akumo_nugget_250gr.png',
            'PRD-EX-008' => 'products/prd_071_alfa_one.png',
            'PRD-EX-009' => 'products/prd_072_allana_daging_kerbau_1kg.png',
            'PRD-EX-010' => 'products/prd_073_amroon_1_kg.png',
            'PRD-EX-011' => 'products/prd_074_asimo_nugget_250gr.png',
            'PRD-EX-012' => 'products/prd_075_ayam_ungkep_1_kg.png',
            'PRD-EX-013' => 'products/prd_076_ayam_ungkep_500_gr.png',
            'PRD-EX-014' => 'products/prd_077_b19_bakso_ayam_200gr.png',
            'PRD-EX-015' => 'products/prd_078_b19_bakso_basreng.png',
            'PRD-EX-016' => 'products/prd_079_b19_bakso_ikan_250gr.png',
            'PRD-EX-017' => 'products/prd_080_bakpow_karakter.png',
            'PRD-EX-018' => 'products/prd_081_bakso_basreng_rb.png',
            'PRD-EX-019' => 'products/prd_082_bakso_bms_isi_25.png',
            'PRD-EX-020' => 'products/prd_083_bakso_bul_bul_hijau.png',
            'PRD-EX-021' => 'products/prd_084_bakso_bul_bul_kuning.png',
            'PRD-EX-022' => 'products/prd_085_bakso_bul_bul_merah.png',
            'PRD-EX-023' => 'products/prd_086_bakso_bul_bul_ungu.png',
            'PRD-EX-024' => 'products/prd_087_bakso_iman_sa.png',
            'PRD-EX-025' => 'products/prd_088_bakso_iman_sapi.png',
            'PRD-EX-026' => 'products/prd_089_bakso_jawara_isi_100.png',
            'PRD-EX-027' => 'products/prd_090_bakso_kahiji.png',
            'PRD-EX-028' => 'products/prd_091_bakso_mekar_sari_kembang_jeruk.png',
            'PRD-EX-029' => 'products/prd_092_bakso_sedap_daging_cincang.png',
            'PRD-EX-030' => 'products/prd_093_bakso_sedap_sari_keju.png',
            'PRD-EX-031' => 'products/prd_094_bakso_sumber_selera_original.png',
            'PRD-EX-032' => 'products/prd_095_bakso_tusuk_kirana.png',
            'PRD-EX-033' => 'products/prd_096_bartoz_nugget_500gr.png',
            'PRD-EX-034' => 'products/prd_097_basreng_umkm_all_varian_250_gr.png',
            'PRD-EX-035' => 'products/prd_098_bawang_goreng_toples_kecil.png',
            'PRD-EX-036' => 'products/prd_099_be_best_daging_kerbau_1kg.png',
            'PRD-EX-037' => 'products/prd_100_bebek_1_3_kg.png',
            'PRD-EX-038' => 'products/prd_101_bebek_frozen_1_8_kg.png',
            'PRD-EX-039' => 'products/prd_102_bebek_peking_1_kg.png',
            'PRD-EX-040' => 'products/prd_103_bebek_peking_2_1_kg.png',
            'PRD-EX-041' => 'products/prd_104_belfood_chicken_nugget_ayam_25.png',
            'PRD-EX-042' => 'products/prd_105_belfood_kentang_175gr.png',
            'PRD-EX-043' => 'products/prd_106_belfood_nugget_ceria_170gr.png',
            'PRD-EX-044' => 'products/prd_107_belfood_nugget_ceria_500gr.png',
            'PRD-EX-045' => 'products/prd_108_belfood_nugget_sp_170gr.png',
            'PRD-EX-046' => 'products/prd_109_belfood_nugget_stik_170gr.png',
            'PRD-EX-047' => 'products/prd_110_belfood_nugget_uenak_220gr.png',
            'PRD-EX-048' => 'products/prd_111_belfood_nugget_uenak_500gr.png',
            'PRD-EX-049' => 'products/prd_112_belfood_royal_nugget_470gr.png',
            'PRD-EX-050' => 'products/prd_113_belfood_sosis_475_gr_isi_15.png',
            'PRD-EX-051' => 'products/prd_114_belfood_sosis_ayam_200gr.png',
            'PRD-EX-052' => 'products/prd_115_belfood_sosis_isi_30.png',
            'PRD-EX-053' => 'products/prd_116_belibis_saus_tomat_340ml.png',
            'PRD-EX-054' => 'products/prd_117_belibis_saus_cabe_135ml.png',
            'PRD-EX-055' => 'products/prd_118_belibis_saus_cabe_1kg.png',
            'PRD-EX-056' => 'products/prd_119_belibis_saus_cabe_340ml.png',
            'PRD-EX-057' => 'products/prd_120_belibis_saus_tomat_135ml.png',
            'PRD-EX-058' => 'products/prd_121_bella_white_chocolate_250gr.png',
            'PRD-EX-059' => 'products/prd_122_berkat.png',
            'PRD-EX-060' => 'products/prd_123_bms_isi_50.png',
            'PRD-EX-061' => 'products/prd_124_boba_1_kg.png',
            'PRD-EX-062' => 'products/prd_125_bolen_kujang.png',
            'PRD-EX-063' => 'products/prd_126_bolen_lembang_kang_sule.png',
            'PRD-EX-064' => 'products/prd_127_bon_cabe_lv_10_botol_4_5_g.png',
            'PRD-EX-065' => 'products/prd_128_bon_cabe_nori_sachet.png',
            'PRD-EX-066' => 'products/prd_129_bonanza.png',
            'PRD-EX-067' => 'products/prd_130_bonbon_sosis_1kg.png',
            'PRD-EX-068' => 'products/prd_131_bonbon_sosis_500gr.png',
            'PRD-EX-069' => 'products/prd_132_boneka_koper_oct_84018.png',
            'PRD-EX-070' => 'products/prd_133_bosque_sosis_bakar_mini.png',
            'PRD-EX-071' => 'products/prd_134_bravo_daging_rendang_1_kg.png',
            'PRD-EX-072' => 'products/prd_135_bubble_jelly.png',
            'PRD-EX-073' => 'products/prd_136_bumbu_bakso_sony.png',
            'PRD-EX-074' => 'products/prd_137_bumifood_crab_stik_50_g.png',
            'PRD-EX-075' => 'products/prd_138_bumifood_fish_tofu_60_gr.png',
            'PRD-EX-076' => 'products/prd_139_bumifood_odeng_60_gr.png',
            'PRD-EX-077' => 'products/prd_140_bun_mini.png',
            'PRD-EX-078' => 'products/prd_141_bun_wijen.png',
            'PRD-EX-079' => 'products/prd_142_cedea_bakso_salmon_500gr.png',
            'PRD-EX-080' => 'products/prd_143_cedea_chikuwa_long_1kg.png',
            'PRD-EX-081' => 'products/prd_144_bakso_bahari_ikan_ayam.png',
            'PRD-EX-082' => 'products/prd_145_bakso_ikan_sinar_bahari_isi_10.png',
            'PRD-EX-083' => 'products/prd_146_bakso_sumber_selera_keju.png',
            'PRD-EX-084' => 'products/prd_147_barcelona_1_kg.png',
            'PRD-EX-085' => 'products/prd_148_barcelona_100_g.png',
            'PRD-EX-086' => 'products/prd_149_barcelona_250_g.png',
            'PRD-EX-087' => 'products/prd_150_barcelona_50_g.png',
            'PRD-EX-088' => 'products/prd_151_barcelona_500_g.png',
            'PRD-EX-089' => 'products/prd_152_basreng_50_g.png',
            'PRD-EX-090' => 'products/prd_153_basreng_origina_1_kg.png',
            'PRD-EX-091' => 'products/prd_154_basreng_origina_100_g.png',
            'PRD-EX-092' => 'products/prd_155_basreng_origina_250_g.png',
            'PRD-EX-093' => 'products/prd_156_basreng_origina_50_g.png',
            'PRD-EX-094' => 'products/prd_157_basreng_origina_500_g.png',
            'PRD-EX-095' => 'products/prd_158_basreng_toples_500_gr.png',
            'PRD-EX-096' => 'products/prd_159_basreng_toples_1_kg.png',
            'PRD-EX-097' => 'products/prd_160_basreng_toples_250_gr.png',
            'PRD-EX-098' => 'products/prd_161_bika_ambon.png',
            'PRD-EX-099' => 'products/prd_162_bolu_bandung.png',
            'PRD-EX-100' => 'products/prd_163_bon_cabe_lv_15_botol.png',
            'PRD-EX-101' => 'products/prd_164_bon_cabe_lv_30.png',
            'PRD-EX-102' => 'products/prd_165_bon_cabe_lv_30_sachet_4_5_g.png',
            'PRD-EX-103' => 'products/prd_166_bon_cabe_lv_50_maxed_sachet_2_.png',
            'PRD-EX-104' => 'products/prd_167_bumbu_pecel_sinti_100gr.png',
            'PRD-EX-105' => 'products/prd_168_cabe_kering_250gr.png',
            'PRD-EX-106' => 'products/prd_169_astor_all_varian.png',
            'PRD-EX-107' => 'products/prd_170_astor_all_varian_250_gr.png',
            'PRD-EX-108' => 'products/prd_171_bola_pelangi.png',
            'PRD-EX-109' => 'products/prd_172_dodol_kertas_eka_sari_1_kg.png',
            'PRD-EX-110' => 'products/prd_173_dodol_kertas_ekasari_250_gr.png',
            'PRD-EX-111' => 'products/prd_174_dodol_kertas_eksari_500_gr.png',
            'PRD-EX-112' => 'products/prd_175_dodol_warna.png',
            'PRD-EX-113' => 'products/prd_176_gem_kembang_ball.png',
            'PRD-EX-114' => 'products/prd_177_jeli_inaco_1_kg.png',
            'PRD-EX-115' => 'products/prd_178_jeli_inaco_500_gr.png',
            'PRD-EX-116' => 'products/prd_179_hasan_isi_6.png',
            'PRD-EX-117' => 'products/prd_180_hasanah_isi_6.png',
            'PRD-EX-118' => 'products/prd_181_jeli_bit_1_kg.png',
            'PRD-EX-119' => 'products/prd_182_jeli_bit_500_gr.png',
            'PRD-EX-120' => 'products/prd_183_kacang_atom_100_gr.png',
            'PRD-EX-121' => 'products/prd_184_aice_2_colors.png',
            'PRD-EX-122' => 'products/prd_185_aice_chocolate_crispy.png',
            'PRD-EX-123' => 'products/prd_186_aice_cofee_crispy.png',
            'PRD-EX-124' => 'products/prd_187_aice_ember_5_liter.png',
            'PRD-EX-125' => 'products/prd_188_aice_ember_8_liter.png',
            'PRD-EX-126' => 'products/prd_189_cimory_bites_120_ml.png',
            'PRD-EX-127' => 'products/prd_190_cimory_eatmilk.png',
            'PRD-EX-128' => 'products/prd_191_cimory_pororo_325_ml.png',
            'PRD-EX-129' => 'products/prd_192_cimory_squeze.png',
            'PRD-EX-130' => 'products/prd_193_cimory_uht_125_ml.png',
            'PRD-EX-131' => 'products/prd_194_bakso_mozzarella.png',
            'PRD-EX-132' => 'products/prd_195_bakso_pentol_kecil.png',
            'PRD-EX-133' => 'products/prd_196_bakso_rusuk.png',
            'PRD-EX-134' => 'products/prd_197_bakso_rusuk_biasa.png',
            'PRD-EX-135' => 'products/prd_198_bakso_rusuk_jumbo.png',
            'PRD-EX-136' => 'products/prd_199_bakso_bul.png',
            'PRD-EX-137' => 'products/prd_200_bintang.png',
            'PRD-EX-138' => 'products/prd_201_bola_salmon.png',
            'PRD-EX-139' => 'products/prd_202_chikua.png',
            'PRD-EX-140' => 'products/prd_203_duo_flowers.png',
            'PRD-EX-141' => 'products/prd_204_adabi_rempah_sup_tulang_13_gr.png',
            'PRD-EX-142' => 'products/prd_205_asam_jawa.png',
            'PRD-EX-143' => 'products/prd_206_biji_pala_37_gr.png',
            'PRD-EX-144' => 'products/prd_207_del_monte_bbq_250_gr.png',
            'PRD-EX-145' => 'products/prd_208_del_monte_extra_hot_sachet_8_g.png',
            'PRD-EX-146' => 'products/prd_209_dua_belibis_saos_cabe_1_kg.png',
            'PRD-EX-147' => 'products/prd_210_156_mobil_tumbling.png',
            'PRD-EX-148' => 'products/prd_211_627_8_paw_patrol.png',
            'PRD-EX-149' => 'products/prd_212_6602b_boneka_padat.png',
            'PRD-EX-150' => 'products/prd_213_99_818_pistol_rambo.png',
            'PRD-0214' => 'products/prd_214_bumbu_rendang.png',
            'PRD-0215' => 'products/prd_215_bumbu_opor.png',
        ];

        foreach ($products as $p) {
            $kat = Kategori::where('nama', $p['kat'])->first();
            $katId = $kat ? $kat->id : 1;
            $img = isset($imgMap[$p['kode']]) ? $imgMap[$p['kode']] : null;

            $prod = Produk::where('nama', $p['nama'])->orWhere('kode_produk', $p['kode'])->first();
            if ($prod) {
                if ($img) $prod->update(['gambar' => $img]);
            } else {
                Produk::create([
                    'kode_produk'   => $p['kode'],
                    'kategori_id'   => $katId,
                    'nama'          => $p['nama'],
                    'harga'         => $p['harga'],
                    'stok'          => $p['stok'],
                    'stok_minimum'  => $p['min'],
                    'satuan'        => $p['sat'],
                    'deskripsi'     => $p['desk'],
                    'gambar'        => $img,
                    'status'        => 'active',
                ]);
            }
        }
    }
}